-- Insert Display Cabinet Products (30 total)
INSERT INTO public.products (id, name, price, description, category, badge, is_active) VALUES
-- From existing code (25 products)
(gen_random_uuid(), 'Curved Glass Display Cabinet', '$4,500', 'Premium curved glass refrigerated display case for pastries and desserts', 'Display Cabinets', 'Best Seller', true),
(gen_random_uuid(), 'Heated Food Display Warmer', '$3,200', 'Self-service heated display cabinet for hot food items', 'Display Cabinets', 'New', true),
(gen_random_uuid(), 'Gelato Display Showcase', '$6,800', 'Italian-style gelato display case with scooping wells', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Bakery Tower Display', '$2,800', 'Multi-tier rotating display for baked goods', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Deli Meat Slicer Case', '$5,500', 'Refrigerated deli display with integrated slicer', 'Display Cabinets', 'Best Seller', true),
(gen_random_uuid(), 'Chocolate Display Cooler', '$4,200', 'Temperature-controlled chocolate display cabinet', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Sushi Display Refrigerator', '$7,500', 'Specialized sushi display with precise temperature control', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Wine Display Cabinet', '$3,800', 'Temperature-controlled wine display with UV protection', 'Display Cabinets', 'New', true),
(gen_random_uuid(), 'Salad Bar Display Cooler', '$4,800', 'Open-top refrigerated salad bar with sneeze guards', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Pizza Display Warmer', '$2,400', 'Heated pizza display case for slice service', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Sandwich Display Cooler', '$3,600', 'Refrigerated sandwich and wrap display case', 'Display Cabinets', 'Best Seller', true),
(gen_random_uuid(), 'Ice Cream Display Freezer', '$8,200', 'Curved glass ice cream display freezer', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Donut Display Case', '$1,800', 'Clear acrylic donut display with tiered shelving', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Cheese Display Cabinet', '$5,200', 'Specialty cheese aging and display cabinet', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Hot Dog Roller Display', '$1,200', 'Heated roller display for hot dogs and sausages', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Seafood Display Case', '$6,500', 'Refrigerated seafood display with crushed ice system', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Popcorn Display Warmer', '$950', 'Heated popcorn display with warming lights', 'Display Cabinets', 'New', true),
(gen_random_uuid(), 'Pretzel Display Warmer', '$1,800', 'Heated pretzel display with humidity control', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Coffee Cup Display Warmer', '$650', 'Heated cup and lid dispenser with warming plate', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Chicken Rotisserie Display', '$4,500', 'Heated rotisserie chicken display cabinet', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Breakfast Pastry Display', '$2,200', 'Ambient temperature pastry display with multiple tiers', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Smoothie Ingredient Display', '$3,400', 'Refrigerated ingredient display for smoothie bars', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Candy Bulk Display Bins', '$1,600', 'Self-serve candy display bins with scoops', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Frozen Yogurt Display', '$7,800', 'Soft-serve frozen yogurt display cabinet', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Soup Display Warmer', '$2,800', 'Heated soup display with ladle wells', 'Display Cabinets', NULL, true),
-- Additional 5 products to reach 30
(gen_random_uuid(), 'Burrito Display Warmer', '$3,200', 'Heated display case for wrapped burritos and wraps', 'Display Cabinets', 'New', true),
(gen_random_uuid(), 'Cake Display Refrigerator', '$5,800', 'Multi-tier cake display with LED lighting', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Bagel Display Tower', '$1,900', 'Rotating bagel display with clear compartments', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Nacho Chip Warmer', '$1,400', 'Heated display for nachos and tortilla chips', 'Display Cabinets', NULL, true),
(gen_random_uuid(), 'Muffin Display Case', '$2,600', 'Temperature-controlled muffin display cabinet', 'Display Cabinets', 'Best Seller', true);

-- Insert Commercial Refrigeration Products (30 total)
INSERT INTO public.products (id, name, price, description, category, badge, is_active) VALUES
-- From existing code (25 products)
(gen_random_uuid(), 'One Door Cabinet', '$8,500', 'Pre-fabricated walk-in cooler with insulated panels', 'Commercial Refrigeration', 'Best Seller', true),
(gen_random_uuid(), 'Blast Chiller Cabinet', '$22,000', 'Rapid cooling technology for food safety compliance', 'Commercial Refrigeration', 'New', true),
(gen_random_uuid(), 'Reach-in Freezer 3-Door', '$8,500', 'Heavy-duty three-door reach-in freezer', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Under-counter Refrigerator', '$3,200', 'Compact under-counter refrigeration unit', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Wine Storage Cabinet', '$4,800', 'Temperature-controlled wine storage with dual zones', 'Commercial Refrigeration', 'Best Seller', true),
(gen_random_uuid(), 'Freezer Room 10x12', '$28,500', 'Custom freezer room with advanced insulation', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Prep Table Refrigerator', '$2,800', 'Refrigerated prep table with cutting surface', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Glass Door Merchandiser', '$5,500', 'Glass door refrigerator for beverage display', 'Commercial Refrigeration', 'New', true),
(gen_random_uuid(), 'Ice Storage Bin', '$1,800', 'Insulated ice storage with easy access', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Pharmacy Refrigerator', '$6,200', 'Medical-grade refrigerator for pharmaceutical storage', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Keg Cooler Walk-in', '$18,000', 'Specialized walk-in cooler for keg storage', 'Commercial Refrigeration', 'Best Seller', true),
(gen_random_uuid(), 'Floral Display Cooler', '$4,500', 'Refrigerated display case for fresh flowers', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Meat Aging Cabinet', '$12,500', 'Controlled environment for meat aging process', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Bakery Display Freezer', '$7,200', 'Frozen bakery product display case', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Mortuary Refrigerator', '$25,000', 'Specialized refrigeration for mortuary use', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Laboratory Freezer', '$8,500', 'Scientific-grade freezer for laboratory samples', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Ice Machine 500lb', '$4,200', 'High-capacity ice machine with storage', 'Commercial Refrigeration', 'New', true),
(gen_random_uuid(), 'Combination Unit', '$9,800', 'Half freezer, half refrigerator combination unit', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Reach-in Cooler 2-Door', '$5,500', 'Two-door reach-in refrigerator for general storage', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Shock Freezer Tunnel', '$45,000', 'Industrial shock freezing tunnel system', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Plate Freezer System', '$35,000', 'Horizontal plate freezer for seafood processing', 'Commercial Refrigeration', 'Best Seller', true),
(gen_random_uuid(), 'Spiral Freezer', '$125,000', 'High-capacity spiral freezing system', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Refrigerated Truck Body', '$18,500', 'Insulated truck body for refrigerated transport', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Cold Storage Warehouse', '$250,000', 'Large-scale cold storage facility system', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Refrigerated Trailer', '$55,000', 'Mobile refrigerated trailer for transport', 'Commercial Refrigeration', NULL, true),
-- Additional 5 products to reach 30
(gen_random_uuid(), 'Vaccine Storage Refrigerator', '$7,800', 'Medical-grade vaccine storage with precise temperature control', 'Commercial Refrigeration', 'New', true),
(gen_random_uuid(), 'Blood Bank Refrigerator', '$9,200', 'Specialized refrigeration for blood storage', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Explosion-Proof Freezer', '$15,000', 'Hazardous environment freezer with safety features', 'Commercial Refrigeration', NULL, true),
(gen_random_uuid(), 'Ultra-Low Temperature Freezer', '$18,500', 'Research-grade ultra-low temperature storage', 'Commercial Refrigeration', 'Best Seller', true),
(gen_random_uuid(), 'Mobile Refrigeration Cart', '$3,500', 'Portable refrigerated cart for catering', 'Commercial Refrigeration', NULL, true);

-- Insert Professional Kitchen Equipment Products (30 total)  
INSERT INTO public.products (id, name, price, description, category, badge, is_active) VALUES
-- From existing code (25 products)
(gen_random_uuid(), 'Industrial Convection Oven', '$12,500', 'High-performance convection oven with digital controls and steam injection', 'Professional Kitchen Equipment', 'Best Seller', true),
(gen_random_uuid(), 'Commercial Gas Range', '$8,900', 'Professional 6-burner gas range with griddle and double oven', 'Professional Kitchen Equipment', 'New', true),
(gen_random_uuid(), 'Walk-in Blast Freezer', '$25,000', 'Rapid freezing technology for preserving food quality', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Mixer 60Qt', '$3,500', 'Heavy-duty planetary mixer for high-volume production', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Combi Steamer Oven', '$18,500', 'Multi-function cooking with steam and convection capabilities', 'Professional Kitchen Equipment', 'Best Seller', true),
(gen_random_uuid(), 'Industrial Fryer Dual Basket', '$6,800', 'High-capacity dual basket fryer with oil filtration', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Dishwasher', '$4,200', 'High-temperature sanitizing dishwasher', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Professional Food Processor', '$2,800', 'Heavy-duty food processor for prep work', 'Professional Kitchen Equipment', 'New', true),
(gen_random_uuid(), 'Salamander Broiler', '$1,900', 'Overhead broiler for finishing and browning', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Ice Machine', '$3,200', 'High-output ice machine with storage bin', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Tilting Braising Pan', '$15,600', 'Versatile tilting pan for braising, searing, and sautéing', 'Professional Kitchen Equipment', 'Best Seller', true),
(gen_random_uuid(), 'Commercial Griddle 48"', '$4,500', 'Large flat-top griddle for high-volume cooking', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Vacuum Chamber Sealer', '$5,500', 'Professional vacuum sealing for food preservation', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Smoker', '$8,200', 'Large capacity smoker for BBQ and specialty items', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Pasta Cooker Station', '$3,800', 'Dedicated pasta cooking station with baskets', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Dough Sheeter', '$6,500', 'Precision dough rolling for bakery operations', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Blast Chiller Cabinet', '$12,800', 'Rapid cooling technology for food safety', 'Professional Kitchen Equipment', 'New', true),
(gen_random_uuid(), 'Commercial Coffee Machine', '$4,800', 'Professional espresso machine for café service', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Induction Cooktop Station', '$2,200', 'Energy-efficient induction cooking surface', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Meat Slicer', '$1,800', 'Precision slicing for deli and food prep', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Rotisserie Oven', '$7,500', 'Self-basting rotisserie for poultry and roasts', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Warmer Cabinet', '$2,400', 'Food holding cabinet with humidity control', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Pressure Steamer', '$9,200', 'High-pressure steaming for fast cooking', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Proofing Cabinet', '$3,600', 'Controlled environment for dough proofing', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Ultrasonic Cleaner', '$1,500', 'Precision cleaning for small parts and utensils', 'Professional Kitchen Equipment', NULL, true),
-- Additional 5 products to reach 30
(gen_random_uuid(), 'Commercial Pizza Oven', '$15,800', 'High-temperature deck oven for pizza production', 'Professional Kitchen Equipment', 'New', true),
(gen_random_uuid(), 'Automatic Slicer System', '$8,900', 'Automated slicing system for high-volume operations', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Char Broiler', '$5,200', 'Heavy-duty char broiler for grilled specialties', 'Professional Kitchen Equipment', 'Best Seller', true),
(gen_random_uuid(), 'Industrial Blender Station', '$3,800', 'High-power blending station for smoothies and sauces', 'Professional Kitchen Equipment', NULL, true),
(gen_random_uuid(), 'Commercial Wok Station', '$4,600', 'High-BTU wok cooking station with accessories', 'Professional Kitchen Equipment', NULL, true);