// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zutxcudhkfhlaxbkaahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1dHhjdWRoa2ZobGF4YmthYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjU4NzAsImV4cCI6MjA3Mzc0MTg3MH0.y-1mDXA4nTtTG5lCVvjaPEqq9BPJtProKBJzQtdQDPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});